Models/Autore.cs
using csharp_bibliotecaMvc.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace csharp_bibliotecaMvc.Models
{
    public class Autore
    {
        [Column(Order = 1), System.ComponentModel.DataAnnotations.Key]

        public string Cognome { get; set; }
        [Column(Order = 2), System.ComponentModel.DataAnnotations.Key]

        public string Nome { get; set; }
        [Column(Order = 3), System.ComponentModel.DataAnnotations.Key]

        public DateTime DataNascita { get; set; }

        public ICollection<Libro>? Libri { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace csharp_bibliotecaMvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Libro.cs
using System.ComponentModel.DataAnnotations;

namespace csharp_bibliotecaMvc.Models
{
    public enum Stato
    { 
        Disponibile,
        Prestato,
    }

    public class Libro
    {
        public int LibroID { get; set; }

        public string Titolo { get; set; }

        public int Anno { get; set; }

        public string Stato { get; set; }

        public string? ISBN { get; set; }

        public int? Scaffale { get; set; }
        public List<Autore>? Autori { get; set; }   
        
        public virtual ICollection<Prestito>? Prestito { get; set; }
    }
}

Models/Prestito.cs
namespace csharp_bibliotecaMvc.Models
{
    public class Prestito
    {
        public string PrestitoID { get; set; }

        public DateTime Inizio { get; set; }

        public DateTime Fine { get; set; }

        public int UtenteID { get; set; }

        public int LibroID { get; set; }

        public virtual Libro Libro { get; set; }

        public virtual Utente Utente { get; set; }
    }
}

Models/Utente.cs
namespace csharp_bibliotecaMvc.Models
{
    public class Utente
    {
        public int UtenteID { get; set; }

        public string Nome { get; set; }

        public string Cognome { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }

        public virtual ICollection<Prestito> Prestito { get; set; }
    }
}

Controllers/HomeController.cs
using csharp_bibliotecaMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace csharp_bibliotecaMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LibroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using csharp_bibliotecaMvc.Data;
using csharp_bibliotecaMvc.Models;

namespace csharp_bibliotecaMvc.Controllers
{
    public class LibroesController : Controller
    {
        private readonly BibliotecaContext _context;

        public LibroesController(BibliotecaContext context)
        {
            _context = context;
        }

        // GET: Libroes
        public async Task<IActionResult> Index()
        {
              return _context.Libris != null ? 
                          View(await _context.Libris.ToListAsync()) :
                          Problem("Entity set 'BibliotecaContext.Libris'  is null.");
        }

        // GET: Libroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Libris == null)
            {
                return NotFound();
            }

            var libro = await _context.Libris.Where(m => m.LibroID == id).Include(p => p.Prestito).ToListAsync();
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // GET: Libroes/Create
        public IActionResult Create()
        {
            //Libro myLibro = new Libro();
            //myLibro.Autori.Add(new Autore { Nome = "Dante", Cognome = "Alighieri", DataNascita = DateTime.Parse("26/04/1340") });
            //myLibro.Autori.Add(new Autore { Nome = "Giorgio", Cognome = "Bocca", DataNascita = DateTime.Parse("26/04/1933") });
            ViewData["listaAutori"] = _context.Autores.ToList<Autore>();

            return View();
        }

        // POST: Libroes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Libro libro)
        {
            if (ModelState.IsValid)
            {
                string[] str = Request.Form["AutoreData"];
                for (int i = 0; i < str.Length; i++)
                {
                    string[] words = str[i].Split(',');
                    Autore nuovo = new Autore() { Nome = words[0], Cognome = words[1], DataNascita = DateTime.Parse(words[2]) };
                    libro.Autori.Add(nuovo);
                    _context.Add(libro);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(libro);
        }

        // GET: Libroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Libris == null)
            {
                return NotFound();
            }

            var libro = await _context.Libris.FindAsync(id);
            if (libro == null)
            {
                return NotFound();
            }
            return View(libro);
        }

        // POST: Libroes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LibroID,Titolo,Anno,Stato,ISBN")] Libro libro)
        {
            if (id != libro.LibroID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(libro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.LibroID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(libro);
        }

        // GET: Libroes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Libris == null)
            {
                return NotFound();
            }

            var libro = await _context.Libris
                .FirstOrDefaultAsync(m => m.LibroID == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // POST: Libroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Libris == null)
            {
                return Problem("Entity set 'BibliotecaContext.Libris'  is null.");
            }
            var libro = await _context.Libris.FindAsync(id);
            if (libro != null)
            {
                _context.Libris.Remove(libro);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool LibroExists(int id)
        {
          return (_context.Libris?.Any(e => e.LibroID == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a href="@Url.Action("Index", "Libroes")">Esplora i libri</a>
</div>

Views/Libroes/Create.cshtml
@model csharp_bibliotecaMvc.Models.Libro

@{
    ViewData["Title"] = "Create";
}
@using (Html.BeginForm("Create", "Libroes", FormMethod.Post))
{
    <table cellpadding="0" cellspacing="0" class="center">
        <tr>
            <th colspan="2" align="center">Inserisci i dati del libro:</th>
        </tr>
        <tr>
            <td><p style="color:red;font-weight: bold;">Titolo: </p></td>
            <td>
                @Html.TextBoxFor(m => m.Titolo)
            </td>
        </tr>
        <tr>
            <td><p style="color:red;font-weight: bold;">Scaffale:</p> </td>
            <td>
                @Html.TextBoxFor(m => m.Scaffale)
            </td>
        </tr>
        <tr>
            <td><p style="color:red;font-weight: bold;">Anno:</p> </td>
            <td>
                @Html.TextBoxFor(m => m.Anno)
            </td>
        </tr>
        <tr>
            <td><p style="color:red;font-weight: bold;">ISBN:</p> </td>
            <td>
                @Html.TextBoxFor(m => m.ISBN)
            </td>
        </tr>
        <tr>
            <td><p style="color:red;font-weight: bold;">Stato: </p></td>
            <td>
                @Html.DropDownListFor(m => m.Stato, new List<SelectListItem>
                { new SelectListItem{Text="Libero", Value="Libero"},
                    new SelectListItem{Text="In prestito", Value="InPrestito"}}, "Please select")
            </td>
        </tr>
        <tr>
            <td><p style="color:red;font-weight: bold;">Lista autori: </p></td>
            <td> 
                <select name="AutoreData" id="autori-select" multiple> 
                @foreach(var aut  in ViewData["listaAutori"] as List<Autore>)
                {
                    <option value ="@aut.Nome,@aut.Cognome,@aut.DataNascita">@aut.Nome @aut.Cognome</option>
                }
                </select>
            </td>
        </tr>
        <tr id="input-container">
            <td><p style="color:red;font-weight: bold;">Lista autori</p></td>
        </tr>
        <tr>
            <td><button type="button" class="btn btn-primary" id="add-inputs">Aggiungi Autore</button></td>
            <td><input type="submit" value="Submit"/></td>
        </tr>
    </table>
}

@section Scripts
{
  <script>
    const addInputAuth = document.getElementById("add-inputs");
    const inputContainer = document.getElementById("input-container");
    let currIndex = 0;
    addInputAuth.addEventListener('click',(e)=>{
        const newTd = document.createElement("td");
        newTd.innerHTML = `<input data-val="true" data-val-required="The Cognome field is required." id="Autori_${currIndex}__Cognome" name="Autori${currIndex}.Cognome" type="text"  />
                        <input data-val="true" data-val-required="The Nome field is required." id="Autori_${currIndex}__Nome" name="Autori${currIndex}.Nome" type="text" />
                        <input data-val="true" data-val-required="The DataNascita field is required." id="Autori_${currIndex}__DataNascita" name="Autori${currIndex}.DataNascita" type="text" value="01/01/1300 00:00:00" />`
        inputContainer.appendChild(newTd);
        currIndex += 1;
    });
  </script>
}

Views/Libroes/Delete.cshtml
@model csharp_bibliotecaMvc.Models.Libro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titolo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titolo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stato)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stato)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LibroID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Libroes/Details.cshtml
@model csharp_bibliotecaMvc.Models.Libro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titolo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titolo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stato)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stato)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.LibroID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Libroes/Edit.cshtml
@model csharp_bibliotecaMvc.Models.Libro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LibroID" />
            <div class="form-group">
                <label asp-for="Titolo" class="control-label"></label>
                <input asp-for="Titolo" class="form-control" />
                <span asp-validation-for="Titolo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anno" class="control-label"></label>
                <input asp-for="Anno" class="form-control" />
                <span asp-validation-for="Anno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stato" class="control-label"></label>
                <input asp-for="Stato" class="form-control" />
                <span asp-validation-for="Stato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Libroes/Index.cshtml
@model IEnumerable<csharp_bibliotecaMvc.Models.Libro>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titolo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Anno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titolo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Anno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.LibroID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.LibroID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.LibroID">Delete</a>
                <a asp-action="AddAutore" asp-route-id="@item.LibroID">Aggiungi Autore</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - csharp_bibliotecaMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/csharp_bibliotecaMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">csharp_bibliotecaMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - csharp_bibliotecaMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>